Gnuplot Class Reference
#include <gnuplot_i.hpp>
Public Member Functions
Gnuplot (const std::string &style=`points`)
set a style during construction
Gnuplot (const std::vector< double > &x, const std::string &title=``, const std::string &style=`points`, const std::string &labelx=`x`, const std::string &labely=`y`)
plot a single std::vector at one go
Gnuplot (const std::vector< double > &x, const std::vector< double > &y, const std::string &title=``, const std::string &style=`points`, const std::string &labelx=`x`, const std::string &labely=`y`)
plot pairs std::vector at one go
Gnuplot (const std::vector< double > &x, const std::vector< double > &y, const std::vector< double > &z, const std::string &title=``, const std::string &style=`points`, const std::string &labelx=`x`, const std::string &labely=`y`, const std::string &labelz=`z`)
plot triples std::vector at one go
~Gnuplot ()
destructor: needed to delete temporary files
Gnuplot & cmd (const std::string &cmdstr)
send a command to gnuplot
Gnuplot & operator<< (const std::string &cmdstr)
Sends a command to an active gnuplot session, identical to cmd() send a command to gnuplot using the << operator.
Gnuplot & showonscreen ()
sets terminal type to terminal_std
Gnuplot & savetops (const std::string &filename=`gnuplot_output`)
saves a gnuplot session to a postscript file, filename without extension
Gnuplot & set_style (const std::string &stylestr=`points`)
Gnuplot & set_smooth (const std::string &stylestr=`csplines`)
Gnuplot & unset_smooth ()
unset smooth attention: smooth is not set by default
Gnuplot & set_pointsize (const double pointsize=1.0)
scales the size of the points used in plots
Gnuplot & set_grid ()
turns grid on/off
Gnuplot & unset_grid ()
grid is not set by default
Gnuplot & set_multiplot ()
Gnuplot & unset_multiplot ()
Gnuplot & set_samples (const int samples=100)
set sampling rate of functions, or for interpolating data
Gnuplot & set_isosamples (const int isolines=10)
set isoline density (grid) for plotting functions as surfaces (for 3d plots)
Gnuplot & set_hidden3d ()
Gnuplot & unset_hidden3d ()
Gnuplot & set_contour (const std::string &position=`base`)
Gnuplot & unset_contour ()
Gnuplot & set_surface ()
Gnuplot & unset_surface ()
Gnuplot & set_legend (const std::string &position=`default`)
Gnuplot & unset_legend ()
Switches legend off attention:legend is set by default.
Gnuplot & set_title (const std::string &title=``)
sets and clears the title of a gnuplot session
Gnuplot & unset_title ()
Clears the title of a gnuplot session The title is not set by default.
Gnuplot & set_ylabel (const std::string &label=`x`)
set x axis label
Gnuplot & set_xlabel (const std::string &label=`y`)
set y axis label
Gnuplot & set_zlabel (const std::string &label=`z`)
set z axis label
Gnuplot & set_xrange (const double iFrom, const double iTo)
set axis - ranges
Gnuplot & set_yrange (const double iFrom, const double iTo)
set y-axis - ranges
Gnuplot & set_zrange (const double iFrom, const double iTo)
set z-axis - ranges
Gnuplot & set_xautoscale ()
Gnuplot & set_yautoscale ()
Gnuplot & set_zautoscale ()
Gnuplot & set_xlogscale (const double base=10)
turns on/off log scaling for the specified xaxis (logscale is not set by default)
Gnuplot & set_ylogscale (const double base=10)
turns on/off log scaling for the specified yaxis (logscale is not set by default)
Gnuplot & set_zlogscale (const double base=10)
turns on/off log scaling for the specified zaxis (logscale is not set by default)
Gnuplot & unset_xlogscale ()
Gnuplot & unset_ylogscale ()
Gnuplot & unset_zlogscale ()
Gnuplot & set_cbrange (const double iFrom, const double iTo)
set palette range (autoscale by default)
Gnuplot & plotfile_x (const std::string &filename, const unsigned int column=1, const std::string &title=``)
template<typename X >
Gnuplot & plot_x (const X &x, const std::string &title=``)
from std::vector
Gnuplot & plotfile_xy (const std::string &filename, const unsigned int column_x=1, const unsigned int column_y=2, const std::string &title=``)
template<typename X , typename Y >
Gnuplot & plot_xy (const X &x, const Y &y, const std::string &title=``)
from data
Gnuplot & plotfile_xy_err (const std::string &filename, const unsigned int column_x=1, const unsigned int column_y=2, const unsigned int column_dy=3, const std::string &title=``)
template<typename X , typename Y , typename E >
Gnuplot & plot_xy_err (const X &x, const Y &y, const E &dy, const std::string &title=``)
from data
Gnuplot & plotfile_xyz (const std::string &filename, const unsigned int column_x=1, const unsigned int column_y=2, const unsigned int column_z=3, const std::string &title=``)
template<typename X , typename Y , typename Z >
Gnuplot & plot_xyz (const X &x, const Y &y, const Z &z, const std::string &title=``)
from std::vector
Gnuplot & plot_slope (const double a, const double b, const std::string &title=``)
plot an equation of the form: y = ax + b, you supply a and b
Gnuplot & plot_equation (const std::string &equation, const std::string &title=``)
Gnuplot & plot_equation3d (const std::string &equation, const std::string &title=``)
Gnuplot & plot_image (const unsigned char *ucPicBuf, const unsigned int iWidth, const unsigned int iHeight, const std::string &title=``)
plot image
Gnuplot & replot (void)
replot repeats the last plot or splot command. this can be useful for viewing a plot with different set options, or when generating the same plot for several devices (showonscreen, savetops)
Gnuplot & reset_plot ()
resets a gnuplot session (next plot will erase previous ones)
Gnuplot & reset_all ()
resets a gnuplot session and sets all variables to default
void remove_tmpfiles ()
deletes temporary files
bool is_valid ()
Is the gnuplot session valid ??
Static Public Member Functions
static bool set_GNUPlotPath (const std::string &path)
optional function: set Gnuplot path manual attention: for windows: path with slash '/' not backslash '\'
static void set_terminal_std (const std::string &type)
Detailed Description
Definition at line 68 of file gnuplot_i.hpp.
Constructor & Destructor Documentation
Gnuplot::Gnuplot (const std::string & style = `points`) [inline]
set a style during construction
Definition at line 612 of file gnuplot_i.hpp.
References set_style().
613                            :gnucmd(NULL) ,valid(false) ,two_dim(false) ,nplots(0)
614 
615 {
616     init();
617     set_style(style);
618 }
Gnuplot::Gnuplot (const std::vector< double > & x, const std::string & title = ``, const std::string & style = `points`, const std::string & labelx = `x`, const std::string & labely = `y`) [inline]
plot a single std::vector at one go
Definition at line 624 of file gnuplot_i.hpp.
References plot_x(), set_style(), set_xlabel(), and set_ylabel().
629                            :gnucmd(NULL) ,valid(false) ,two_dim(false) ,nplots(0)
630 {
631     init();
632 
633     set_style(style);
634     set_xlabel(labelx);
635     set_ylabel(labely);
636 
637     plot_x(x,title);
638 }
Gnuplot::Gnuplot (const std::vector< double > & x, const std::vector< double > & y, const std::string & title = ``, const std::string & style = `points`, const std::string & labelx = `x`, const std::string & labely = `y`) [inline]
plot pairs std::vector at one go
Definition at line 645 of file gnuplot_i.hpp.
References plot_xy(), set_style(), set_xlabel(), and set_ylabel().
651                            :gnucmd(NULL) ,valid(false) ,two_dim(false) ,nplots(0)
652 {
653     init();
654 
655     set_style(style);
656     set_xlabel(labelx);
657     set_ylabel(labely);
658 
659     plot_xy(x,y,title);
660 }
Gnuplot::Gnuplot (const std::vector< double > & x, const std::vector< double > & y, const std::vector< double > & z, const std::string & title = ``, const std::string & style = `points`, const std::string & labelx = `x`, const std::string & labely = `y`, const std::string & labelz = `z`) [inline]
plot triples std::vector at one go
Definition at line 667 of file gnuplot_i.hpp.
References plot_xyz(), set_style(), set_xlabel(), set_ylabel(), and set_zlabel().
675                            :gnucmd(NULL) ,valid(false) ,two_dim(false) ,nplots(0)
676 {
677     init();
678 
679     set_style(style);
680     set_xlabel(labelx);
681     set_ylabel(labely);
682     set_zlabel(labelz);
683 
684     plot_xyz(x,y,z,title);
685 }
Gnuplot::~Gnuplot ()
destructor: needed to delete temporary files
Definition at line 944 of file gnuplot_i.hpp.
945 {
946 //  remove_tmpfiles();
947 
948     // A stream opened by popen() should be closed by pclose()
949 #if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__TOS_WIN__)
950     if (_pclose(gnucmd) == -1)
951 #elif defined(unix) || defined(__unix) || defined(__unix__) || defined(__APPLE__)
952     if (pclose(gnucmd) == -1)
953 #endif
954         throw GnuplotException("Problem closing communication to gnuplot");
955 }
Member Function Documentation
Gnuplot & Gnuplot::cmd (const std::string & cmdstr)
send a command to gnuplot
Definition at line 1641 of file gnuplot_i.hpp.
Referenced by main(), operator<<(), plot_equation(), plot_equation3d(), plot_image(), plot_slope(), plotfile_x(), plotfile_xy(), plotfile_xy_err(), plotfile_xyz(), replot(), reset_all(), savetops(), set_cbrange(), set_contour(), set_grid(), set_hidden3d(), set_isosamples(), set_legend(), set_multiplot(), set_pointsize(), set_samples(), set_surface(), set_xautoscale(), set_xlabel(), set_xlogscale(), set_xrange(), set_yautoscale(), set_ylabel(), set_ylogscale(), set_yrange(), set_zautoscale(), set_zlabel(), set_zlogscale(), set_zrange(), showonscreen(), unset_contour(), unset_grid(), unset_hidden3d(), unset_legend(), unset_multiplot(), unset_surface(), unset_xlogscale(), unset_ylogscale(), and unset_zlogscale().
1642 {
1643     if( !(valid) )
1644     {
1645         return *this;
1646     }
1647 
1648 
1649     // int fputs ( const char * str, FILE * stream );
1650     // writes the string str to the stream.
1651     // The function begins copying from the address specified (str) until it 
1652     // reaches the terminating null character ('\0'). This final 
1653     // null-character is not copied to the stream.
1654     fputs( (cmdstr+"\n").c_str(), gnucmd );
1655 
1656     // int fflush ( FILE * stream );
1657     // If the given stream was open for writing and the last i/o operation was 
1658     // an output operation, any unwritten data in the output buffer is written 
1659     // to the file.  If the argument is a null pointer, all open files are 
1660     // flushed.  The stream remains open after this call.
1661     fflush(gnucmd);
1662 
1663 
1664     if( cmdstr.find("replot") != std::string::npos )
1665     {
1666         return *this;
1667     }
1668     else if( cmdstr.find("splot") != std::string::npos )
1669     {
1670         two_dim = false;
1671         nplots++;
1672     }
1673     else if( cmdstr.find("plot") != std::string::npos )
1674     {
1675         two_dim = true;
1676         nplots++;
1677     }
1678 
1679     return *this;
1680 }
bool Gnuplot::is_valid () [inline]
Is the gnuplot session valid ??
Parameters:
---
Returns: true if valid, false if not
Definition at line 582 of file gnuplot_i.hpp.
582 {return(valid);};
Gnuplot& Gnuplot::operator<< (const std::string & cmdstr) [inline]
Sends a command to an active gnuplot session, identical to cmd() send a command to gnuplot using the << operator.
Parameters:
cmdstr --> the command string
Returns: <-- a reference to the gnuplot object
Definition at line 220 of file gnuplot_i.hpp.
References cmd().
220                                                        {
221         cmd(cmdstr);
222         return(*this);
223     }
Gnuplot & Gnuplot::plot_equation (const std::string & equation, const std::string & title = ``)
plot an equation supplied as a std::string y=f(x), write only the function f(x) not y= the independent variable has to be x binary operators: ** exponentiation, * multiply, / divide, + add, - substract, % modulo unary operators: - minus, ! factorial elementary functions: rand(x), abs(x), sgn(x), ceil(x), floor(x), int(x), imag(x), real(x), arg(x), sqrt(x), exp(x), log(x), log10(x), sin(x), cos(x), tan(x), asin(x), acos(x), atan(x), atan2(y,x), sinh(x), cosh(x), tanh(x), asinh(x), acosh(x), atanh(x) special functions: erf(x), erfc(x), inverf(x), gamma(x), igamma(a,x), lgamma(x), ibeta(p,q,x), besj0(x), besj1(x), besy0(x), besy1(x), lambertw(x) statistical fuctions: norm(x), invnorm(x)
Definition at line 1345 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1347 {
1348     std::ostringstream cmdstr;
1349     //
1350     // command to be sent to gnuplot
1351     //
1352     if (nplots > 0  &&  two_dim == true)
1353         cmdstr << "replot ";
1354     else
1355         cmdstr << "plot ";
1356 
1357     cmdstr << equation << " title \"";
1358 
1359     if (title == "")
1360         cmdstr << "f(x) = " << equation;
1361     else
1362         cmdstr << title;
1363 
1364     cmdstr << "\" with " << pstyle;
1365 
1366     //
1367     // Do the actual plot
1368     //
1369     cmd(cmdstr.str());
1370 
1371     return *this;
1372 }
Gnuplot & Gnuplot::plot_equation3d (const std::string & equation, const std::string & title = ``)
plot an equation supplied as a std::string z=f(x,y), write only the function f(x,y) not z= the independent variables have to be x and y
Definition at line 1378 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1380 {
1381     std::ostringstream cmdstr;
1382     //
1383     // command to be sent to gnuplot
1384     //
1385     if (nplots > 0  &&  two_dim == false)
1386         cmdstr << "replot ";
1387     else
1388         cmdstr << "splot ";
1389 
1390     cmdstr << equation << " title \"";
1391 
1392     if (title == "")
1393         cmdstr << "f(x,y) = " << equation;
1394     else
1395         cmdstr << title;
1396 
1397     cmdstr << "\" with " << pstyle;
1398 
1399     //
1400     // Do the actual plot
1401     //
1402     cmd(cmdstr.str());
1403 
1404     return *this;
1405 }
Gnuplot & Gnuplot::plot_image (const unsigned char * ucPicBuf, const unsigned int iWidth, const unsigned int iHeight, const std::string & title = ``)
plot image
* note that this function is not valid for versions of GNUPlot below 4.2
Definition at line 1586 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1590 {
1591     std::ofstream tmp;
1592     std::string name = create_tmpfile(tmp);
1593     if (name == "")
1594         return *this;
1595 
1596     //
1597     // write the data to file
1598     //
1599     int iIndex = 0;
1600     for(int iRow = 0; iRow < iHeight; iRow++)
1601     {
1602         for(int iColumn = 0; iColumn < iWidth; iColumn++)
1603         {
1604             tmp << iColumn << " " << iRow  << " " 
1605                 << static_cast<float>(ucPicBuf[iIndex++]) << std::endl;
1606         }
1607     }
1608 
1609     tmp.flush();
1610     tmp.close();
1611 
1612 
1613     std::ostringstream cmdstr;
1614     //
1615     // command to be sent to gnuplot
1616     //
1617     if (nplots > 0  &&  two_dim == true)
1618         cmdstr << "replot ";
1619     else
1620         cmdstr << "plot ";
1621 
1622     if (title == "")
1623         cmdstr << "\"" << name << "\" with image";
1624     else
1625         cmdstr << "\"" << name << "\" title \"" << title << "\" with image";
1626 
1627     //
1628     // Do the actual plot
1629     //
1630     cmd(cmdstr.str());
1631 
1632     return *this;
1633 }
Gnuplot & Gnuplot::plot_slope (const double a, const double b, const std::string & title = ``)
plot an equation of the form: y = ax + b, you supply a and b
Definition at line 1311 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1314 {
1315     std::ostringstream cmdstr;
1316     //
1317     // command to be sent to gnuplot
1318     //
1319     if (nplots > 0  &&  two_dim == true)
1320         cmdstr << "replot ";
1321     else
1322         cmdstr << "plot ";
1323 
1324     cmdstr << a << " * x + " << b << " title \"";
1325 
1326     if (title == "")
1327         cmdstr << "f(x) = " << a << " * x + " << b;
1328     else
1329         cmdstr << title;
1330 
1331     cmdstr << "\" with " << pstyle;
1332 
1333     //
1334     // Do the actual plot
1335     //
1336     cmd(cmdstr.str());
1337 
1338     return *this;
1339 }
template<typename X > Gnuplot & Gnuplot::plot_x (const X & x, const std::string & title = ``) [inline]
from std::vector
Plots a 2d graph from a list of doubles: x.
Definition at line 693 of file gnuplot_i.hpp.
References plotfile_x().
Referenced by Gnuplot(), and main().
694 {
695     if (x.size() == 0)
696     {
697         throw GnuplotException("std::vector too small");
698         return *this;
699     }
700 
701     std::ofstream tmp;
702     std::string name = create_tmpfile(tmp);
703     if (name == "")
704         return *this;
705 
706     //
707     // write the data to file
708     //
709     for (unsigned int i = 0; i < x.size(); i++)
710         tmp << x[i] << std::endl;
711 
712     tmp.flush();
713     tmp.close();
714 
715 
716     plotfile_x(name, 1, title);
717 
718     return *this;
719 }
template<typename X , typename Y > Gnuplot & Gnuplot::plot_xy (const X & x, const Y & y, const std::string & title = ``) [inline]
from data
Plots a 2d graph from a list of doubles: x y.
Definition at line 727 of file gnuplot_i.hpp.
References plotfile_xy().
Referenced by Gnuplot(), and main().
728 {
729     if (x.size() == 0 || y.size() == 0)
730     {
731         throw GnuplotException("std::vectors too small");
732         return *this;
733     }
734 
735     if (x.size() != y.size())
736     {
737         throw GnuplotException("Length of the std::vectors differs");
738         return *this;
739     }
740 
741 
742     std::ofstream tmp;
743     std::string name = create_tmpfile(tmp);
744     if (name == "")
745         return *this;
746 
747     //
748     // write the data to file
749     //
750     for (unsigned int i = 0; i < x.size(); i++)
751         tmp << x[i] << " " << y[i] << std::endl;
752 
753     tmp.flush();
754     tmp.close();
755 
756 
757     plotfile_xy(name, 1, 2, title);
758 
759     return *this;
760 }
template<typename X , typename Y , typename E > Gnuplot & Gnuplot::plot_xy_err (const X & x, const Y & y, const E & dy, const std::string & title = ``) [inline]
from data
-----------------------------------------------------------------------------
plot x,y pairs with dy errorbars
Definition at line 767 of file gnuplot_i.hpp.
References plotfile_xy_err().
Referenced by main().
771 {
772     if (x.size() == 0 || y.size() == 0 || dy.size() == 0)
773     {
774         throw GnuplotException("std::vectors too small");
775         return *this;
776     }
777 
778     if (x.size() != y.size() || y.size() != dy.size())
779     {
780         throw GnuplotException("Length of the std::vectors differs");
781         return *this;
782     }
783 
784 
785     std::ofstream tmp;
786     std::string name = create_tmpfile(tmp);
787     if (name == "")
788         return *this;
789 
790     //
791     // write the data to file
792     //
793     for (unsigned int i = 0; i < x.size(); i++)
794         tmp << x[i] << " " << y[i] << " " << dy[i] << std::endl;
795 
796     tmp.flush();
797     tmp.close();
798 
799 
800     // Do the actual plot
801     plotfile_xy_err(name, 1, 2, 3, title);
802 
803     return *this;
804 }
template<typename X , typename Y , typename Z > Gnuplot & Gnuplot::plot_xyz (const X & x, const Y & y, const Z & z, const std::string & title = ``) [inline]
from std::vector
Definition at line 812 of file gnuplot_i.hpp.
References plotfile_xyz().
Referenced by Gnuplot(), and main().
816 {
817     if (x.size() == 0 || y.size() == 0 || z.size() == 0)
818     {
819         throw GnuplotException("std::vectors too small");
820         return *this;
821     }
822 
823     if (x.size() != y.size() || x.size() != z.size())
824     {
825         throw GnuplotException("Length of the std::vectors differs");
826         return *this;
827     }
828 
829 
830     std::ofstream tmp;
831     std::string name = create_tmpfile(tmp);
832     if (name == "")
833         return *this;
834 
835     //
836     // write the data to file
837     //
838     for (unsigned int i = 0; i < x.size(); i++)
839         tmp << x[i] << " " << y[i] << " " << z[i] <<std::endl;
840 
841     tmp.flush();
842     tmp.close();
843 
844 
845     plotfile_xyz(name, 1, 2, 3, title);
846 
847     return *this;
848 }
Gnuplot & Gnuplot::plotfile_x (const std::string & filename, const unsigned int column = 1, const std::string & title = ``)
plot a single std::vector: x from file
Definition at line 1412 of file gnuplot_i.hpp.
References cmd().
Referenced by plot_x().
1415 {
1416     //
1417     // check if file exists
1418     //
1419     file_available(filename);
1420 
1421 
1422     std::ostringstream cmdstr;
1423     //
1424     // command to be sent to gnuplot
1425     //
1426     if (nplots > 0  &&  two_dim == true)
1427         cmdstr << "replot ";
1428     else
1429         cmdstr << "plot ";
1430 
1431     cmdstr << "\"" << filename << "\" using " << column;
1432 
1433     if (title == "")
1434         cmdstr << " notitle ";
1435     else
1436         cmdstr << " title \"" << title << "\" ";
1437 
1438     if(smooth == "")
1439         cmdstr << "with " << pstyle;
1440     else
1441         cmdstr << "smooth " << smooth;
1442 
1443     //
1444     // Do the actual plot
1445     //
1446     cmd(cmdstr.str()); //nplots++; two_dim = true;  already in cmd();
1447 
1448     return *this;
1449 }
Gnuplot & Gnuplot::plotfile_xy (const std::string & filename, const unsigned int column_x = 1, const unsigned int column_y = 2, const std::string & title = ``)
plot x,y pairs: x y from file
Definition at line 1457 of file gnuplot_i.hpp.
References cmd().
Referenced by plot_xy().
1461 {
1462     //
1463     // check if file exists
1464     //
1465     file_available(filename);
1466 
1467 
1468     std::ostringstream cmdstr;
1469     //
1470     // command to be sent to gnuplot
1471     //
1472     if (nplots > 0  &&  two_dim == true)
1473         cmdstr << "replot ";
1474     else
1475         cmdstr << "plot ";
1476 
1477     cmdstr << "\"" << filename << "\" using " << column_x << ":" << column_y;
1478 
1479     if (title == "")
1480         cmdstr << " notitle ";
1481     else
1482         cmdstr << " title \"" << title << "\" ";
1483 
1484     if(smooth == "")
1485         cmdstr << "with " << pstyle;
1486     else
1487         cmdstr << "smooth " << smooth;
1488 
1489     //
1490     // Do the actual plot
1491     //
1492     cmd(cmdstr.str());
1493 
1494     return *this;
1495 }
Gnuplot & Gnuplot::plotfile_xy_err (const std::string & filename, const unsigned int column_x = 1, const unsigned int column_y = 2, const unsigned int column_dy = 3, const std::string & title = ``)
plot x,y pairs with dy errorbars: x y dy from file
Definition at line 1502 of file gnuplot_i.hpp.
References cmd().
Referenced by plot_xy_err().
1507 {
1508     //
1509     // check if file exists
1510     //
1511     file_available(filename);
1512 
1513     std::ostringstream cmdstr;
1514     //
1515     // command to be sent to gnuplot
1516     //
1517     if (nplots > 0  &&  two_dim == true)
1518         cmdstr << "replot ";
1519     else
1520         cmdstr << "plot ";
1521 
1522     cmdstr << "\"" << filename << "\" using " 
1523            << column_x << ":" << column_y << ":" << column_dy 
1524            << " with errorbars ";
1525 
1526     if (title == "")
1527         cmdstr << " notitle ";
1528     else
1529         cmdstr << " title \"" << title << "\" ";
1530 
1531     //
1532     // Do the actual plot
1533     //
1534     cmd(cmdstr.str());
1535 
1536     return *this;
1537 }
Gnuplot & Gnuplot::plotfile_xyz (const std::string & filename, const unsigned int column_x = 1, const unsigned int column_y = 2, const unsigned int column_z = 3, const std::string & title = ``)
plot x,y,z triples: x y z from file
Definition at line 1544 of file gnuplot_i.hpp.
References cmd().
Referenced by plot_xyz().
1549 {
1550     //
1551     // check if file exists
1552     //
1553     file_available(filename);
1554 
1555     std::ostringstream cmdstr;
1556     //
1557     // command to be sent to gnuplot
1558     //
1559     if (nplots > 0  &&  two_dim == false)
1560         cmdstr << "replot ";
1561     else
1562         cmdstr << "splot ";
1563 
1564     cmdstr << "\"" << filename << "\" using " << column_x << ":" << column_y 
1565            << ":" << column_z;
1566 
1567     if (title == "")
1568         cmdstr << " notitle with " << pstyle;
1569     else
1570         cmdstr << " title \"" << title << "\" with " << pstyle;
1571 
1572     //
1573     // Do the actual plot
1574     //
1575     cmd(cmdstr.str());
1576 
1577     return *this;
1578 }
void Gnuplot::remove_tmpfiles ()
deletes temporary files
Definition at line 1948 of file gnuplot_i.hpp.
1948                              {
1949     if ((tmpfile_list).size() > 0)
1950     {
1951         for (unsigned int i = 0; i < tmpfile_list.size(); i++)
1952             remove( tmpfile_list[i].c_str() );
1953 
1954         Gnuplot::tmpfile_num -= tmpfile_list.size();
1955     }
1956 }
Gnuplot& Gnuplot::replot (void) [inline]
replot repeats the last plot or splot command. this can be useful for viewing a plot with different set options, or when generating the same plot for several devices (showonscreen, savetops)
Parameters:
---
Returns: ---
Definition at line 563 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
563 {if (nplots > 0) cmd("replot");return *this;};
Gnuplot & Gnuplot::reset_all ()
resets a gnuplot session and sets all variables to default
Definition at line 976 of file gnuplot_i.hpp.
References cmd(), and showonscreen().
Referenced by main().
977 {
978 //  remove_tmpfiles();
979 
980     nplots = 0;
981     cmd("reset");
982     cmd("clear");
983     pstyle = "points";
984     smooth = "";
985     showonscreen();
986 
987     return *this;
988 }
Gnuplot & Gnuplot::reset_plot ()
resets a gnuplot session (next plot will erase previous ones)
Definition at line 962 of file gnuplot_i.hpp.
Referenced by main().
963 {
964 //  remove_tmpfiles();
965 
966     nplots = 0;
967 
968     return *this;
969 }
Gnuplot & Gnuplot::savetops (const std::string & filename = `gnuplot_output`)
saves a gnuplot session to a postscript file, filename without extension
Definition at line 1077 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1078 {
1079     cmd("set terminal postscript color");
1080 
1081     std::ostringstream cmdstr;
1082     cmdstr << "set output \"" << filename << ".ps\"";
1083     cmd(cmdstr.str());
1084 
1085     return *this;
1086 }
Gnuplot & Gnuplot::set_cbrange (const double iFrom, const double iTo)
set palette range (autoscale by default)
Definition at line 1295 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1297 {
1298     std::ostringstream cmdstr;
1299 
1300     cmdstr << "set cbrange[" << iFrom << ":" << iTo << "]";
1301     cmd(cmdstr.str());
1302 
1303     return *this;
1304 }
Gnuplot & Gnuplot::set_contour (const std::string & position = `base`)
enables/disables contour drawing for surfaces (for 3d plot) base, surface, both
Definition at line 1190 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1191 {
1192     if (position.find("base")    == std::string::npos  &&
1193         position.find("surface") == std::string::npos  &&
1194         position.find("both")    == std::string::npos  )
1195     {
1196         cmd("set contour base");
1197     }
1198     else
1199     {
1200         cmd("set contour " + position);
1201     }
1202 
1203     return *this;
1204 }
bool Gnuplot::set_GNUPlotPath (const std::string & path) [static]
optional function: set Gnuplot path manual attention: for windows: path with slash '/' not backslash '\'
Parameters:
path --> the gnuplot path
Returns: true on success, false otherwise
Definition at line 856 of file gnuplot_i.hpp.
857 {
858 
859     std::string tmp = path + "/" + Gnuplot::m_sGNUPlotFileName;
860 
861 
862 #if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__TOS_WIN__)
863     if ( Gnuplot::file_exists(tmp,0) ) // check existence
864 #elif defined(unix) || defined(__unix) || defined(__unix__) || defined(__APPLE__)
865     if ( Gnuplot::file_exists(tmp,1) ) // check existence and execution permission
866 #endif
867     {
868         Gnuplot::m_sGNUPlotPath = path;
869         return true;
870     }
871     else
872     {
873         Gnuplot::m_sGNUPlotPath.clear();
874         return false;
875     }
876 }
Gnuplot& Gnuplot::set_grid () [inline]
turns grid on/off
Definition at line 266 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
266 {cmd("set grid");return *this;};
Gnuplot& Gnuplot::set_hidden3d () [inline]
enables/disables hidden line removal for surface plotting (for 3d plot)
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 302 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
302 {cmd("set hidden3d");return *this;};
Gnuplot & Gnuplot::set_isosamples (const int isolines = 10)
set isoline density (grid) for plotting functions as surfaces (for 3d plots)
Definition at line 1175 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1176 {
1177     std::ostringstream cmdstr;
1178     cmdstr << "set isosamples " << isolines;
1179     cmd(cmdstr.str());
1180 
1181     return *this;
1182 }
Gnuplot & Gnuplot::set_legend (const std::string & position = `default`)
switches legend on/off position: inside/outside, left/center/right, top/center/bottom, nobox/box
Definition at line 1092 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1093 {
1094     std::ostringstream cmdstr;
1095     cmdstr << "set key " << position;
1096 
1097     cmd(cmdstr.str());
1098 
1099     return *this;
1100 }
Gnuplot& Gnuplot::set_multiplot () [inline]
set the mulitplot mode
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 277 of file gnuplot_i.hpp.
References cmd().
277 {cmd("set multiplot") ;return *this;};
Gnuplot & Gnuplot::set_pointsize (const double pointsize = 1.0)
scales the size of the points used in plots
Definition at line 1148 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1149 {
1150     std::ostringstream cmdstr;
1151     cmdstr << "set pointsize " << pointsize;
1152     cmd(cmdstr.str());
1153 
1154     return *this;
1155 }
Gnuplot & Gnuplot::set_samples (const int samples = 100)
set sampling rate of functions, or for interpolating data
Definition at line 1161 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1162 {
1163     std::ostringstream cmdstr;
1164     cmdstr << "set samples " << samples;
1165     cmd(cmdstr.str());
1166 
1167     return *this;
1168 }
Gnuplot & Gnuplot::set_smooth (const std::string & stylestr = `csplines`)
interpolation and approximation of data, arguments: csplines, bezier, acsplines (for data values > 0), sbezier, unique, frequency (works only with plot_x, plot_xy, plotfile_x, plotfile_xy (if smooth is set, set_style has no effekt on data plotting)
Definition at line 1041 of file gnuplot_i.hpp.
Referenced by main().
1042 {
1043     if (stylestr.find("unique")    == std::string::npos  &&
1044         stylestr.find("frequency") == std::string::npos  &&
1045         stylestr.find("csplines")  == std::string::npos  &&
1046         stylestr.find("acsplines") == std::string::npos  &&
1047         stylestr.find("bezier")    == std::string::npos  &&
1048         stylestr.find("sbezier")   == std::string::npos  )
1049     {
1050         smooth = "";
1051     }
1052     else
1053     {
1054         smooth = stylestr;
1055     }
1056 
1057     return *this;
1058 }
Gnuplot & Gnuplot::set_style (const std::string & stylestr = `points`)
set line style (some of these styles require additional information): lines, points, linespoints, impulses, dots, steps, fsteps, histeps, boxes, histograms, filledcurves
Definition at line 995 of file gnuplot_i.hpp.
Referenced by Gnuplot(), and main().
996 {
997     if (stylestr.find("lines")          == std::string::npos  &&
998         stylestr.find("points")         == std::string::npos  &&
999         stylestr.find("linespoints")    == std::string::npos  &&
1000         stylestr.find("impulses")       == std::string::npos  &&
1001         stylestr.find("dots")           == std::string::npos  &&
1002         stylestr.find("steps")          == std::string::npos  &&
1003         stylestr.find("fsteps")         == std::string::npos  &&
1004         stylestr.find("histeps")        == std::string::npos  &&
1005         stylestr.find("boxes")          == std::string::npos  &&  // 1-4 columns of data are required
1006         stylestr.find("filledcurves")   == std::string::npos  &&
1007         stylestr.find("histograms")     == std::string::npos  )   //only for one data column
1008 //        stylestr.find("labels")         == std::string::npos  &&  // 3 columns of data are required
1009 //        stylestr.find("xerrorbars")     == std::string::npos  &&  // 3-4 columns of data are required
1010 //        stylestr.find("xerrorlines")    == std::string::npos  &&  // 3-4 columns of data are required
1011 //        stylestr.find("errorbars")      == std::string::npos  &&  // 3-4 columns of data are required
1012 //        stylestr.find("errorlines")     == std::string::npos  &&  // 3-4 columns of data are required
1013 //        stylestr.find("yerrorbars")     == std::string::npos  &&  // 3-4 columns of data are required
1014 //        stylestr.find("yerrorlines")    == std::string::npos  &&  // 3-4 columns of data are required
1015 //        stylestr.find("boxerrorbars")   == std::string::npos  &&  // 3-5 columns of data are required
1016 //        stylestr.find("xyerrorbars")    == std::string::npos  &&  // 4,6,7 columns of data are required
1017 //        stylestr.find("xyerrorlines")   == std::string::npos  &&  // 4,6,7 columns of data are required
1018 //        stylestr.find("boxxyerrorbars") == std::string::npos  &&  // 4,6,7 columns of data are required
1019 //        stylestr.find("financebars")    == std::string::npos  &&  // 5 columns of data are required
1020 //        stylestr.find("candlesticks")   == std::string::npos  &&  // 5 columns of data are required
1021 //        stylestr.find("vectors")        == std::string::npos  &&
1022 //        stylestr.find("image")          == std::string::npos  &&
1023 //        stylestr.find("rgbimage")       == std::string::npos  &&
1024 //        stylestr.find("pm3d")           == std::string::npos  )
1025     {
1026         pstyle = std::string("points");
1027     }
1028     else
1029     {
1030         pstyle = stylestr;
1031     }
1032 
1033     return *this;
1034 }
Gnuplot& Gnuplot::set_surface () [inline]
enables/disables the display of surfaces (for 3d plot)
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 332 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
332 {cmd("set surface");return *this;}; 
void Gnuplot::set_terminal_std (const std::string & type) [static]
optional: set standart terminal, used by showonscreen defaults: Windows - win, Linux - x11, Mac - aqua
Parameters:
type --> the terminal type
Returns: ---
Definition at line 884 of file gnuplot_i.hpp.
885 {
886 #if defined(unix) || defined(__unix) || defined(__unix__) || defined(__APPLE__)
887     if (type.find("x11") != std::string::npos && getenv("DISPLAY") == NULL)
888     {
889         throw GnuplotException("Can't find DISPLAY variable");
890     }
891 #endif
892 
893 
894     Gnuplot::terminal_std = type;
895     return;
896 }
Gnuplot& Gnuplot::set_title (const std::string & title = ``) [inline]
sets and clears the title of a gnuplot session
Parameters:
title --> the title of the plot [optional, default == ``]
Returns: <-- reference to the gnuplot object
Definition at line 366 of file gnuplot_i.hpp.
Referenced by main(), and unset_title().
367     {
368         std::string cmdstr;
369         cmdstr = "set title \"";
370         cmdstr+=title;
371         cmdstr+="\"";
372         *this<<cmdstr;
373         return *this;
374     }
Gnuplot& Gnuplot::set_xautoscale () [inline]
autoscale axis (set by default) of xaxis
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 409 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
409 {cmd("set xrange restore");cmd("set autoscale x");return *this;};
Gnuplot & Gnuplot::set_xlabel (const std::string & label = `y`)
set y axis label
Definition at line 1211 of file gnuplot_i.hpp.
References cmd().
Referenced by Gnuplot(), and main().
1212 {
1213     std::ostringstream cmdstr;
1214 
1215     cmdstr << "set xlabel \"" << label << "\"";
1216     cmd(cmdstr.str());
1217 
1218     return *this;
1219 }
Gnuplot & Gnuplot::set_xlogscale (const double base = 10)
turns on/off log scaling for the specified xaxis (logscale is not set by default)
Definition at line 1106 of file gnuplot_i.hpp.
References cmd().
1107 {
1108     std::ostringstream cmdstr;
1109 
1110     cmdstr << "set logscale x " << base;
1111     cmd(cmdstr.str());
1112 
1113     return *this;
1114 }
Gnuplot & Gnuplot::set_xrange (const double iFrom, const double iTo)
set axis - ranges
Definition at line 1252 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1254 {
1255     std::ostringstream cmdstr;
1256 
1257     cmdstr << "set xrange[" << iFrom << ":" << iTo << "]";
1258     cmd(cmdstr.str());
1259 
1260     return *this;
1261 }
Gnuplot& Gnuplot::set_yautoscale () [inline]
autoscale axis (set by default) of yaxis
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 418 of file gnuplot_i.hpp.
References cmd().
418 {cmd("set yrange restore");cmd("set autoscale y");return *this;};
Gnuplot & Gnuplot::set_ylabel (const std::string & label = `x`)
set x axis label
Definition at line 1224 of file gnuplot_i.hpp.
References cmd().
Referenced by Gnuplot(), and main().
1225 {
1226     std::ostringstream cmdstr;
1227 
1228     cmdstr << "set ylabel \"" << label << "\"";
1229     cmd(cmdstr.str());
1230 
1231     return *this;
1232 }
Gnuplot & Gnuplot::set_ylogscale (const double base = 10)
turns on/off log scaling for the specified yaxis (logscale is not set by default)
Definition at line 1120 of file gnuplot_i.hpp.
References cmd().
1121 {
1122     std::ostringstream cmdstr;
1123 
1124     cmdstr << "set logscale y " << base;
1125     cmd(cmdstr.str());
1126 
1127     return *this;
1128 }
Gnuplot & Gnuplot::set_yrange (const double iFrom, const double iTo)
set y-axis - ranges
Definition at line 1266 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1268 {
1269     std::ostringstream cmdstr;
1270 
1271     cmdstr << "set yrange[" << iFrom << ":" << iTo << "]";
1272     cmd(cmdstr.str());
1273 
1274     return *this;
1275 }
Gnuplot& Gnuplot::set_zautoscale () [inline]
autoscale axis (set by default) of zaxis
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 427 of file gnuplot_i.hpp.
References cmd().
427 {cmd("set zrange restore");cmd("set autoscale z");return *this;};
Gnuplot & Gnuplot::set_zlabel (const std::string & label = `z`)
set z axis label
Definition at line 1237 of file gnuplot_i.hpp.
References cmd().
Referenced by Gnuplot(), and main().
1238 {
1239     std::ostringstream cmdstr;
1240 
1241     cmdstr << "set zlabel \"" << label << "\"";
1242     cmd(cmdstr.str());
1243 
1244     return *this;
1245 }
Gnuplot & Gnuplot::set_zlogscale (const double base = 10)
turns on/off log scaling for the specified zaxis (logscale is not set by default)
Definition at line 1134 of file gnuplot_i.hpp.
References cmd().
1135 {
1136     std::ostringstream cmdstr;
1137 
1138     cmdstr << "set logscale z " << base;
1139     cmd(cmdstr.str());
1140 
1141     return *this;
1142 }
Gnuplot & Gnuplot::set_zrange (const double iFrom, const double iTo)
set z-axis - ranges
Definition at line 1280 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
1282 {
1283     std::ostringstream cmdstr;
1284 
1285     cmdstr << "set zrange[" << iFrom << ":" << iTo << "]";
1286     cmd(cmdstr.str());
1287 
1288     return *this;
1289 }
Gnuplot & Gnuplot::showonscreen ()
sets terminal type to terminal_std
Definition at line 1065 of file gnuplot_i.hpp.
References cmd().
Referenced by main(), and reset_all().
1066 {
1067     cmd("set output");
1068     cmd("set terminal " + Gnuplot::terminal_std);
1069 
1070     return *this;
1071 }
Gnuplot& Gnuplot::unset_contour () [inline]
contour is not set by default, it disables contour drawing for surfaces
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 323 of file gnuplot_i.hpp.
References cmd().
323 {cmd("unset contour");return *this;};
Gnuplot& Gnuplot::unset_grid () [inline]
grid is not set by default
Definition at line 268 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
268 {cmd("unset grid");return *this;}; 
Gnuplot& Gnuplot::unset_hidden3d () [inline]
hidden3d is not set by default
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 311 of file gnuplot_i.hpp.
References cmd().
311 {cmd("unset hidden3d"); return *this;}; 
Gnuplot& Gnuplot::unset_legend () [inline]
Switches legend off attention:legend is set by default.
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 357 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
357 {cmd("unset key"); return *this;}
Gnuplot& Gnuplot::unset_multiplot () [inline]
unsets the mulitplot mode
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 286 of file gnuplot_i.hpp.
References cmd().
286 {cmd("unset multiplot");return *this;};
Gnuplot& Gnuplot::unset_smooth () [inline]
unset smooth attention: smooth is not set by default
Parameters:
---
Returns: <-- a reference to a gnuplot object
Definition at line 259 of file gnuplot_i.hpp.
Referenced by main().
259 { smooth = ""; return *this;}; 
Gnuplot& Gnuplot::unset_surface () [inline]
surface is set by default, it disables the display of surfaces (for 3d plot)
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 342 of file gnuplot_i.hpp.
References cmd().
Referenced by main().
342 {cmd("unset surface"); return *this;}
Gnuplot& Gnuplot::unset_title () [inline]
Clears the title of a gnuplot session The title is not set by default.
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 384 of file gnuplot_i.hpp.
References set_title().
Referenced by main().
384 {this->set_title();return *this;}
Gnuplot& Gnuplot::unset_xlogscale () [inline]
turns off log scaling for the x axis
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 444 of file gnuplot_i.hpp.
References cmd().
444 {cmd("unset logscale x"); return *this;};
Gnuplot& Gnuplot::unset_ylogscale () [inline]
turns off log scaling for the y axis
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 453 of file gnuplot_i.hpp.
References cmd().
453 {cmd("unset logscale y"); return *this;};
Gnuplot& Gnuplot::unset_zlogscale () [inline]
turns off log scaling for the z axis
Parameters:
---
Returns: <-- reference to the gnuplot object
Definition at line 462 of file gnuplot_i.hpp.
References cmd().
462 {cmd("unset logscale z"); return *this;};
The documentation for this class was generated from the following file:
gnuplot_i.hpp